version: "3.9"

services:
  login-api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env         # PORT, DATABASE_URL, JWT_SECRET
    ports:
      - "3001:3001"
    restart: unless-stopped
